import 'dotenv/config';
import express from 'express';
import cors from 'cors';
import helmet from 'helmet';
import rateLimit from 'express-rate-limit';
import jwt from 'jsonwebtoken';
import mongoose from 'mongoose';
import multer from 'multer';
import path from 'node:path';
import { mkdirSync, readFileSync, unlinkSync } from 'node:fs';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { connectDatabase } from './config/db.js';
import { Admin, Doctor, Service, Patient, Appointment, Review, Gallery, Blog, ContactMessage, DentalRecord, Visit, MedicalDocument } from './models/index.js';
import { protect, protectAdmin, protectPatient } from './middleware/auth.js';
import { notFound, errorHandler } from './middleware/error.js';

const app=express(); app.use(helmet()); app.use(cors({origin:process.env.CLIENT_URL||'http://localhost:5173'})); app.use(express.json({limit:'1mb'})); app.use(rateLimit({windowMs:15*60*1000,max:300}));
const uploadDirectory=path.resolve(fileURLToPath(new URL('./uploads/',import.meta.url)));mkdirSync(uploadDirectory,{recursive:true});
const upload=multer({storage:multer.diskStorage({destination:uploadDirectory,filename:(req,file,done)=>done(null,`${randomUUID()}${path.extname(file.originalname).toLowerCase()}`)}),limits:{fileSize:10*1024*1024,files:1},fileFilter:(req,file,done)=>['application/pdf','image/jpeg','image/png','image/webp'].includes(file.mimetype)?done(null,true):done(Object.assign(new Error('Only PDF, JPEG, PNG, or WebP files are allowed'),{status:400}))});
const resources={doctors:Doctor,services:Service,patients:Patient,reviews:Review,gallery:Gallery,blogs:Blog};
const mainDoctorQuery=()=>{const email=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase();return email?Admin.findOne({email}):Admin.findOne().sort('createdAt');};
const publicQueries={doctors:()=>Doctor.find({status:{$ne:'Inactive'}}).sort('-featured name'),services:()=>Service.find({published:true}).sort('-featured name'),gallery:()=>Gallery.find().sort('-createdAt'),reviews:()=>Review.find({approved:true}).sort('-createdAt'),blogs:()=>Blog.find({published:true}).sort('-createdAt')};
app.get('/api/health',(req,res)=>res.json({ok:true}));
for(const [name,query] of Object.entries(publicQueries)) app.get(`/api/${name}`,async(req,res)=>res.json(await query()));
app.get('/api/services/:slug',async(req,res,next)=>{try{const item=await Service.findOne({slug:req.params.slug,published:true}); if(!item)return res.status(404).json({message:'Service not found'});res.json(item)}catch(e){next(e)}});
app.get('/api/blogs/:slug',async(req,res,next)=>{try{const item=await Blog.findOne({slug:req.params.slug,published:true}); if(!item)return res.status(404).json({message:'Article not found'});res.json(item)}catch(e){next(e)}});
function parseDate(value){if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value))return null;const date=new Date(`${value}T00:00:00.000Z`);return Number.isNaN(date.getTime())?null:date;}
async function availableSlots(date,excludeAppointmentId){const mainDoctor=await mainDoctorQuery();const day=parseDate(date);if(!mainDoctor||!day)return null;const today=new Date();today.setUTCHours(0,0,0,0);if(day<today)return [];const busyQuery={date:{$gte:day,$lt:new Date(day.getTime()+86400000)},time:{$exists:true},status:{$in:['Pending','Confirmed','Rescheduled']}};if(excludeAppointmentId)busyQuery._id={$ne:excludeAppointmentId};const hours=mainDoctor.availability.find(item=>item.dayOfWeek===day.getUTCDay());if(!hours)return [];const toMinutes=value=>{const [hour,minute]=value.split(':').map(Number);return hour*60+minute};const start=toMinutes(hours.startTime),end=toMinutes(hours.endTime),duration=hours.slotMinutes||30;if(!Number.isFinite(start)||!Number.isFinite(end)||start>=end)return [];const busy=await Appointment.find(busyQuery).select('time');const occupied=new Set(busy.map(item=>item.time));const slots=[];for(let minute=start;minute+duration<=end;minute+=duration){if(hours.breakStart&&hours.breakEnd&&minute<toMinutes(hours.breakEnd)&&minute+duration>toMinutes(hours.breakStart))continue;const time=`${String(Math.floor(minute/60)).padStart(2,'0')}:${String(minute%60).padStart(2,'0')}`;if(!occupied.has(time))slots.push(time)}return slots;}
app.get('/api/availability',async(req,res,next)=>{try{const slots=await availableSlots(req.query.date);if(slots===null)return res.status(400).json({message:'Choose a valid date or configure chamber availability'});res.json({slots})}catch(e){next(e)}});
app.get('/api/clinical/availability',protect,async(req,res)=>res.json(req.admin.availability||[]));
app.patch('/api/clinical/availability',protect,async(req,res,next)=>{try{if(!Array.isArray(req.body.availability))return res.status(400).json({message:'Availability must be a list of working days'});const days=new Set();for(const entry of req.body.availability){const validTime=value=>typeof value==='string'&&/^([01]\d|2[0-3]):[0-5]\d$/.test(value);if(!Number.isInteger(entry.dayOfWeek)||entry.dayOfWeek<0||entry.dayOfWeek>6||days.has(entry.dayOfWeek)||!validTime(entry.startTime)||!validTime(entry.endTime)||entry.startTime>=entry.endTime||!Number.isInteger(Number(entry.slotMinutes))||Number(entry.slotMinutes)<5||Number(entry.slotMinutes)>240||Boolean(entry.breakStart)!==Boolean(entry.breakEnd)||(entry.breakStart&&(!validTime(entry.breakStart)||!validTime(entry.breakEnd)||entry.breakStart<entry.startTime||entry.breakEnd>entry.endTime||entry.breakStart>=entry.breakEnd)))return res.status(400).json({message:'Check working days, hours, break, and slot duration'});days.add(entry.dayOfWeek);}req.admin.availability=req.body.availability;await req.admin.save();res.json(req.admin.availability)}catch(e){next(e)}});
app.post('/api/appointments',async(req,res,next)=>{try{const {name,phone,email,date,time,reason,message}=req.body;if(!date||!time||!String(reason||'').trim())return res.status(400).json({message:'Date, time, and a reason for the visit are required'});const day=parseDate(date);if(!day)return res.status(400).json({message:'Choose a valid appointment date'});const mainDoctor=await mainDoctorQuery();if(!mainDoctor)return res.status(503).json({message:'Online booking is not configured yet'});if(!(await availableSlots(date))?.includes(time))return res.status(409).json({message:'That appointment time is no longer available'});let patient=null;const token=req.headers.authorization?.startsWith('Bearer ')?req.headers.authorization.slice(7):null;if(token){const decoded=jwt.verify(token,process.env.JWT_SECRET);if(decoded.role==='patient')patient=await Patient.findById(decoded.id);else if(decoded.role!=='mainDoctor'&&decoded.role!=='admin')return res.status(401).json({message:'Invalid session'});}const normalizedEmail=typeof email==='string'&&email.trim()?email.trim().toLowerCase():undefined;if(!patient&&normalizedEmail){const existing=await Patient.findOne({email:normalizedEmail}).select('+password');if(existing?.password)return res.status(401).json({message:'Sign in to book with this patient account'});patient=existing;}if(!patient){if(typeof name!=='string'||!name.trim()||typeof phone!=='string'||!phone.trim())return res.status(400).json({message:'Name and phone are required for a guest booking'});patient=await Patient.create({name:name.trim(),phone:phone.trim(),email:normalizedEmail});}await DentalRecord.findOneAndUpdate({patient:patient._id},{$setOnInsert:{patient:patient._id}}, {upsert:true,new:true,setDefaultsOnInsert:true});const slotKey=`${mainDoctor._id}:${date}:${time}`;const appointment=await Appointment.create({patient,mainDoctor:mainDoctor._id,date:day,time,reason:String(reason).trim(),message,slotKey});res.status(201).json({message:'Appointment request received',appointment})}catch(e){if(e.code===11000)return res.status(409).json({message:'That appointment time is no longer available'});if(e.name==='JsonWebTokenError'||e.name==='TokenExpiredError')return res.status(401).json({message:'Invalid or expired session'});next(e)}});
app.post('/api/contact',async(req,res,next)=>{try{const item=await ContactMessage.create(req.body);res.status(201).json({message:'Message sent successfully',item})}catch(e){next(e)}});
app.post('/api/auth/login',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const admin=await Admin.findOne({email});const configuredEmail=String(process.env.ADMIN_EMAIL||'').trim().toLowerCase();const mainDoctor=configuredEmail?await Admin.findOne({email:configuredEmail}).select('_id'):await Admin.findOne().sort('createdAt').select('_id');if(!admin||!mainDoctor||String(admin._id)!==String(mainDoctor._id)||!(await admin.comparePassword(req.body.password)))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:admin._id,role:'mainDoctor'},process.env.JWT_SECRET,{expiresIn:'8h'});res.json({token,mainDoctor:{id:admin._id,name:admin.name,email:admin.email}})}catch(e){next(e)}});
app.post('/api/auth/doctor/login',async(req,res,next)=>{try{const email=String(req.body.email||'').trim().toLowerCase();const doctor=await Doctor.findOne({email,status:'Active'}).select('+email +password');if(!doctor||!(await doctor.comparePassword(req.body.password||'')))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:doctor._id,role:'doctor'},process.env.JWT_SECRET,{expiresIn:'8h'});res.json({token,doctor:{id:doctor._id,name:doctor.name,email:doctor.email}})}catch(e){next(e)}});
app.get('/api/clinical/doctors',protectAdmin,async(req,res,next)=>{try{res.json(await Doctor.find().select('+email').sort('name'))}catch(e){next(e)}});
app.patch('/api/clinical/doctors/:id/credentials',protectAdmin,async(req,res,next)=>{try{const doctor=await Doctor.findById(req.params.id).select('+email +password');if(!doctor)return res.status(404).json({message:'Doctor not found'});if(req.body.email!==undefined)doctor.email=String(req.body.email).trim().toLowerCase();if(req.body.password!==undefined){if(typeof req.body.password!=='string'||req.body.password.length<12||Buffer.byteLength(req.body.password)>72)return res.status(400).json({message:'Doctor passwords must be 12 to 72 bytes'});doctor.password=req.body.password;}await doctor.save();res.json({id:doctor._id,name:doctor.name,email:doctor.email,status:doctor.status})}catch(e){next(e)}});
app.patch('/api/clinical/patients/:id/assignment',protectAdmin,async(req,res,next)=>{try{if(!Array.isArray(req.body.doctorIds)||req.body.doctorIds.some(id=>!mongoose.isValidObjectId(id)))return res.status(400).json({message:'Choose valid doctor accounts'});const doctors=await Doctor.find({_id:{$in:req.body.doctorIds},status:'Active'}).select('_id');if(doctors.length!==new Set(req.body.doctorIds.map(String)).size)return res.status(400).json({message:'One or more doctors are inactive or unavailable'});const patient=await Patient.findByIdAndUpdate(req.params.id,{assignedDoctors:doctors.map(doctor=>doctor._id)},{new:true,runValidators:true}).populate('assignedDoctors','name specialization');if(!patient)return res.status(404).json({message:'Patient not found'});res.json(patient)}catch(e){next(e)}});
app.patch('/api/appointments/:id/assignment',protectAdmin,async(req,res,next)=>{try{const doctorId=req.body.doctorId||null;if(doctorId&&(!mongoose.isValidObjectId(doctorId)||!await Doctor.exists({_id:doctorId,status:'Active'})))return res.status(400).json({message:'Choose an active doctor'});const appointment=await Appointment.findByIdAndUpdate(req.params.id,{assignedDoctor:doctorId},{new:true,runValidators:true});if(!appointment)return res.status(404).json({message:'Appointment not found'});if(doctorId)await Patient.updateOne({_id:appointment.patient},{$addToSet:{assignedDoctors:doctorId}});await appointment.populate('patient assignedDoctor');res.json(appointment)}catch(e){next(e)}});
app.post('/api/auth/patient/register',async(req,res,next)=>{try{const {name,phone,email,password,dateOfBirth,gender,address,emergencyContact}=req.body;const normalizedEmail=typeof email==='string'?email.trim().toLowerCase():'';if(typeof name!=='string'||!name.trim()||typeof phone!=='string'||!phone.trim()||!/^\S+@\S+\.\S+$/.test(normalizedEmail)||typeof password!=='string'||password.length<8||Buffer.byteLength(password)>72)return res.status(400).json({message:'Enter a name, phone, valid email, and a password of 8 to 72 bytes'});if(await Patient.exists({email:normalizedEmail}))return res.status(409).json({message:'An account or patient record already exists for this email. Contact the clinic to link your account.'});const patient=await Patient.create({name:name.trim(),phone:phone.trim(),email:normalizedEmail,password,dateOfBirth,gender,address,emergencyContact});await ensureRecord(patient._id);const token=jwt.sign({id:patient._id,role:'patient'},process.env.JWT_SECRET,{expiresIn:'8h'});res.status(201).json({token,patient:{id:patient._id,name:patient.name,email:patient.email,patientId:patient.patientId}})}catch(e){next(e)}});
app.post('/api/auth/patient/login',async(req,res,next)=>{try{const patient=await Patient.findOne({email:String(req.body.email||'').trim().toLowerCase()}).select('+password');if(!patient?.password||!(await patient.comparePassword(req.body.password||'')))return res.status(401).json({message:'Invalid email or password'});const token=jwt.sign({id:patient._id,role:'patient'},process.env.JWT_SECRET,{expiresIn:'8h'});res.json({token,patient:{id:patient._id,name:patient.name,email:patient.email,patientId:patient.patientId}})}catch(e){next(e)}});
app.get('/api/patient/me',protectPatient,async(req,res)=>res.json(req.patient));
app.patch('/api/patient/me',protectPatient,async(req,res,next)=>{try{const allowed=['name','dateOfBirth','age','gender','phone','address','emergencyContact','bloodGroup','occupation'];for(const key of allowed)if(req.body[key]!==undefined)req.patient[key]=req.body[key];await req.patient.save();res.json(req.patient)}catch(e){next(e)}});
app.get('/api/patient/records',protectPatient,async(req,res,next)=>{try{const [record,appointments,visitDocs,documents]=await Promise.all([DentalRecord.findOne({patient:req.patient._id}),Appointment.find({patient:req.patient._id}).populate('doctor service').sort('-date'),Visit.find({patient:req.patient._id,patientVisible:true}).sort('-visitDate'),MedicalDocument.find({patient:req.patient._id,patientVisible:true}).select('-storedName').sort('-createdAt')]);const patientRecord=record?.toObject();if(patientRecord){patientRecord.investigations=patientRecord.investigations.filter(item=>item.patientVisible);patientRecord.prescriptions=patientRecord.prescriptions.filter(item=>item.patientVisible);}const visits=visitDocs.map(visit=>{const item=visit.toObject();item.tests=item.tests.filter(test=>test.patientVisible);item.prescriptions=item.prescriptions.filter(prescription=>prescription.patientVisible);return item});res.json({patient:req.patient,record:patientRecord,appointments,visits,documents})}catch(e){next(e)}});
app.get('/api/dashboard',protectAdmin,async(req,res,next)=>{try{const [appointments,patients,doctors,services,reviews,recent]=await Promise.all([Appointment.countDocuments(),Patient.countDocuments(),Doctor.countDocuments(),Service.countDocuments(),Review.countDocuments(),Appointment.find().populate('patient doctor service assignedDoctor').sort('-createdAt').limit(7)]); const statuses=await Appointment.aggregate([{$group:{_id:'$status',count:{$sum:1}}}]);res.json({counts:{appointments,patients,doctors,services,reviews},statuses,recent})}catch(e){next(e)}});
const recordArrays={toothFindings:'Tooth finding',investigations:'Investigation',diagnosis:'Diagnosis',treatmentPlans:'Treatment plan',prescriptions:'Prescription',followUps:'Follow-up'};
const ensureRecord=async patientId=>DentalRecord.findOneAndUpdate({patient:patientId},{$setOnInsert:{patient:patientId}},{upsert:true,new:true,setDefaultsOnInsert:true});
async function authorizePatient(req,res,next){try{if(req.staffRole==='mainDoctor')return next();const patientId=req.params.patientId||req.params.id;if(!mongoose.isValidObjectId(patientId))return res.status(404).json({message:'Patient not found'});const patient=await Patient.findOne({_id:patientId,assignedDoctors:req.doctor._id}).select('_id');if(!patient)return res.status(404).json({message:'Patient not found'});req.authorizedPatient=patient;next()}catch(error){next(error)}}
async function authorizeVisit(req,res,next){try{const visit=await Visit.findById(req.params.visitId||req.params.id).select('patient');if(!visit)return res.status(404).json({message:'Visit not found'});if(req.staffRole==='doctor'&&!await Patient.exists({_id:visit.patient,assignedDoctors:req.doctor._id}))return res.status(404).json({message:'Visit not found'});req.authorizedVisit=visit;next()}catch(error){next(error)}}
async function authorizeDocument(req,res,next){try{const document=await MedicalDocument.findById(req.params.id).select('patient');if(!document)return res.status(404).json({message:'Document not found'});if(req.staffRole==='doctor'&&!await Patient.exists({_id:document.patient,assignedDoctors:req.doctor._id}))return res.status(404).json({message:'Document not found'});req.authorizedDocument=document;next()}catch(error){next(error)}}
app.get('/api/clinical/dashboard',protect,async(req,res,next)=>{
	try {
		const start=new Date();start.setHours(0,0,0,0);
		const end=new Date(start);end.setDate(end.getDate()+1);
		const patientScope=req.staffRole==='doctor'?{assignedDoctors:req.doctor._id}:{};
		const appointmentScope=req.staffRole==='doctor'?{assignedDoctor:req.doctor._id}:{};
		const assignedPatientIds=req.staffRole==='doctor'?await Patient.distinct('_id',patientScope):null;
		const recordScope=assignedPatientIds?{patient:{$in:assignedPatientIds}}:{};
		const [patients,today,upcoming,pending,completed,legacyFollowUps,openVisitFollowUps,completedFollowUps,recent,appointments,records,visits,upcomingTests,pendingReports]=await Promise.all([
			Patient.countDocuments(patientScope),
			Appointment.countDocuments({...appointmentScope,date:{$gte:start,$lt:end}}),
			Appointment.countDocuments({...appointmentScope,date:{$gte:end},status:{$in:['Pending','Confirmed','Rescheduled']}}),
			Appointment.countDocuments({...appointmentScope,status:'Pending'}),
			Appointment.countDocuments({...appointmentScope,status:'Completed'}),
			DentalRecord.countDocuments({...recordScope,followUps:{$elemMatch:{followUpDate:{$gte:start}}}}),
			Visit.countDocuments({...recordScope,followUpDate:{$gte:start},followUpCompletedAt:null}),
			Visit.countDocuments({...recordScope,followUpCompletedAt:{$gte:start}}),
			Patient.find(patientScope).sort('-createdAt').limit(6),
			Appointment.find({...appointmentScope,date:{$gte:start,$lt:end}}).populate('patient doctor service assignedDoctor').sort('time'),
			DentalRecord.find({...recordScope,'followUps.followUpDate':{$gte:start}}).populate('patient').sort('-updatedAt').limit(10),
			Visit.find({...recordScope,followUpDate:{$gte:start},followUpCompletedAt:null}).populate('patient').sort('followUpDate').limit(10),
			Visit.countDocuments({...recordScope,tests:{$elemMatch:{date:{$gte:start},status:'Pending'}}}),
			MedicalDocument.countDocuments({...recordScope,status:'Uploaded'})
		]);
		const legacy=records.flatMap(record=>(record.followUps||[]).filter(item=>new Date(item.followUpDate)>=start).map(item=>({patient:record.patient,date:item.followUpDate,reason:item.reason,notes:item.notes})));
		const scheduled=visits.map(visit=>({patient:visit.patient,date:visit.followUpDate,reason:visit.followUpReason,notes:visit.followUpNotes}));
		const upcomingFollowUps=[...legacy,...scheduled].sort((a,b)=>new Date(a.date)-new Date(b.date)).slice(0,8);
		const recentProblems=records.flatMap(record=>(record.toothFindings||[]).map(item=>({patient:record.patient,toothNumber:item.toothNumber,problem:item.problem,diagnosis:item.diagnosis,updatedAt:item.updatedAt}))).slice(0,8);
		res.json({counts:{patients,todayAppointments:today,upcomingAppointments:upcoming,pending,completed,followUps:legacyFollowUps+openVisitFollowUps,completedFollowUps,upcomingTests,pendingReports},recentPatients:recent,todayAppointments:appointments,upcomingFollowUps,recentProblems});
	} catch(error) { next(error); }
});
app.get('/api/clinical/tests',protect,async(req,res,next)=>{try{const patientIds=req.staffRole==='doctor'?await Patient.distinct('_id',{assignedDoctors:req.doctor._id}):null;const visitFilter=patientIds?{patient:{$in:patientIds}}:{};const today=new Date();today.setHours(0,0,0,0);const visits=await Visit.find({...visitFilter,tests:{$elemMatch:{date:{$gte:today},status:{$in:['Pending','Completed']}}}}).populate('patient','name patientId phone').select('patient visitDate tests').sort('tests.date');const tests=visits.flatMap(visit=>(visit.tests||[]).filter(test=>test.date&&new Date(test.date)>=today&&(!req.query.status||test.status===req.query.status)).map(test=>({ ...test.toObject(),visitId:visit._id,patient:visit.patient }))).sort((a,b)=>new Date(a.date)-new Date(b.date));res.json(tests)}catch(e){next(e)}});
app.patch('/api/clinical/visits/:id/tests/:testId',protect,authorizeVisit,async(req,res,next)=>{try{const visit=await Visit.findById(req.params.id);const test=visit.tests.id(req.params.testId);if(!test)return res.status(404).json({message:'Test not found'});for(const key of ['date','reason','instructions','status','result','doctorNotes','patientVisible'])if(req.body[key]!==undefined)test[key]=req.body[key];await visit.save();res.json(test)}catch(e){next(e)}});
app.get('/api/clinical/reports',protect,async(req,res,next)=>{try{const patientIds=req.staffRole==='doctor'?await Patient.distinct('_id',{assignedDoctors:req.doctor._id}):null;const filter={...(patientIds?{patient:{$in:patientIds}}:{}),...(req.query.status?{status:req.query.status}:{})};const reports=await MedicalDocument.find(filter).populate('patient','name patientId').sort('-createdAt').select('-storedName');res.json(reports)}catch(e){next(e)}});
app.patch('/api/clinical/documents/:id',protect,authorizeDocument,async(req,res,next)=>{try{const allowed=['status','doctorNote','patientVisible'];const updates={};for(const key of allowed)if(req.body[key]!==undefined)updates[key]=req.body[key];const document=await MedicalDocument.findByIdAndUpdate(req.params.id,updates,{new:true,runValidators:true}).select('-storedName');res.json(document)}catch(e){next(e)}});
app.get('/api/clinical/patients',protect,async(req,res,next)=>{try{const q=String(req.query.q||'').trim();const escaped=q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');const regex=new RegExp(escaped,'i');const matchingAppointment=mongoose.isValidObjectId(q)?await Appointment.findById(q).select('patient'):null;const filter={...(req.staffRole==='doctor'?{assignedDoctors:req.doctor._id}:{}),...(q?{$or:[{patientId:regex},{name:regex},{phone:regex},{email:regex},...(matchingAppointment?[{_id:matchingAppointment.patient}]:[])]}:{})};const patients=await Patient.find(filter).populate('assignedDoctors','name specialization status').sort('-updatedAt').limit(100);res.json(patients)}catch(e){next(e)}});
app.post('/api/clinical/patients',protectAdmin,async(req,res,next)=>{try{const patient=await Patient.create(req.body);await ensureRecord(patient._id);res.status(201).json(patient)}catch(e){next(e)}});
app.get('/api/clinical/patients/:id',protect,authorizePatient,async(req,res,next)=>{try{const patient=await Patient.findById(req.params.id).populate('assignedDoctors','name specialization status');if(!patient)return res.status(404).json({message:'Patient not found'});const [record,appointments,visits,documents]=await Promise.all([ensureRecord(patient._id),Appointment.find({patient:patient._id}).populate('doctor service assignedDoctor').sort('-date'),Visit.find({patient:patient._id}).sort('-visitDate'),MedicalDocument.find({patient:patient._id}).select('-storedName').sort('-createdAt')]);res.json({patient,record,appointments,visits,documents})}catch(e){next(e)}});
app.patch('/api/clinical/patients/:id',protect,authorizePatient,async(req,res,next)=>{try{const allowed=['name','dateOfBirth','age','gender','phone','email','address','emergencyContact','bloodGroup','occupation','notes'];const updates={};for(const key of allowed)if(req.body[key]!==undefined)updates[key]=req.body[key];const patient=await Patient.findByIdAndUpdate(req.params.id,updates,{new:true,runValidators:true});if(!patient)return res.status(404).json({message:'Patient not found'});res.json(patient)}catch(e){next(e)}});
app.delete('/api/clinical/patients/:id',protectAdmin,async(req,res,next)=>{try{const patient=await Patient.findByIdAndDelete(req.params.id);if(!patient)return res.status(404).json({message:'Patient not found'});await Promise.all([DentalRecord.findOneAndDelete({patient:req.params.id}),Appointment.deleteMany({patient:req.params.id}),Visit.deleteMany({patient:req.params.id}),MedicalDocument.deleteMany({patient:req.params.id})]);res.json({message:'Patient record deleted'})}catch(e){next(e)}});
app.patch('/api/clinical/patients/:id/record',protect,authorizePatient,async(req,res,next)=>{try{const record=await ensureRecord(req.params.id);const allowed=['medicalHistory','chiefComplaint','examination','toothFindings','investigations','diagnosis','treatmentPlans','prescriptions','followUps'];for(const key of allowed)if(req.body[key]!==undefined)record[key]=req.body[key];if(req.body.timeline)record.timeline=req.body.timeline;record.timeline.push({type:'Clinical update',title:'Patient record updated',notes:req.body.timelineNote||''});await record.save();res.json(record)}catch(e){next(e)}});
for(const [collection,label] of Object.entries(recordArrays)){app.post(`/api/clinical/patients/:id/${collection}`,protect,authorizePatient,async(req,res,next)=>{try{const record=await ensureRecord(req.params.id);record[collection].push(req.body);record.timeline.push({type:label,title:`${label} added`,notes:req.body.notes||req.body.doctorNotes||''});await record.save();res.status(201).json(record)}catch(e){next(e)}});}
for(const [name,Model] of Object.entries(resources)){ const path=`/api/${name}`; app.get(path,protectAdmin,async(req,res,next)=>{try{res.json(await Model.find().sort('-createdAt'))}catch(e){next(e)}}); app.post(path,protectAdmin,async(req,res,next)=>{try{const item=await Model.create(req.body);res.status(201).json(item)}catch(e){next(e)}}); app.patch(`${path}/:id`,protectAdmin,async(req,res,next)=>{try{const updates={...req.body};if(Model===Patient){delete updates.password;delete updates.patientId;}if(Model===Doctor){delete updates.password;delete updates.email;}const item=await Model.findByIdAndUpdate(req.params.id,updates,{new:true,runValidators:true});if(!item)return res.status(404).json({message:'Record not found'});res.json(item)}catch(e){next(e)}}); app.delete(`${path}/:id`,protectAdmin,async(req,res,next)=>{try{const item=await Model.findByIdAndDelete(req.params.id);if(!item)return res.status(404).json({message:'Record not found'});res.json({message:'Deleted successfully'})}catch(e){next(e)}}); }
app.get('/api/appointments',protect,async(req,res,next)=>{try{const query={};if(req.staffRole==='doctor')query.assignedDoctor=req.doctor._id;if(req.query.date){const date=parseDate(String(req.query.date));if(!date)return res.status(400).json({message:'Choose a valid date'});query.date={$gte:date,$lt:new Date(date.getTime()+86400000)}}if(req.query.scope==='today'){const start=new Date();start.setHours(0,0,0,0);const end=new Date(start);end.setDate(end.getDate()+1);query.date={$gte:start,$lt:end}}else if(req.query.scope==='upcoming'){const start=new Date();start.setHours(0,0,0,0);start.setDate(start.getDate()+1);query.date={$gte:start};query.status={$in:['Pending','Confirmed','Rescheduled']}}if(req.query.status&&['Pending','Confirmed','Completed','Cancelled','Rescheduled'].includes(req.query.status))query.status=req.query.status;if(req.query.doctor&&req.staffRole==='mainDoctor')query.assignedDoctor=req.query.doctor;if(req.query.service)query.service=req.query.service;if(req.query.q){const q=String(req.query.q).trim();const matching=mongoose.isValidObjectId(q)?await Appointment.findById(q).select('_id'):null;if(mongoose.isValidObjectId(q))query._id=matching?matching._id:new mongoose.Types.ObjectId(q);else{const regex=new RegExp(q.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i');const patients=await Patient.find({$or:[{name:regex},{phone:regex},{patientId:regex}]}).select('_id');query.patient={$in:patients.map(patient=>patient._id)}}}res.json(await Appointment.find(query).populate('patient doctor service assignedDoctor').sort('date time'))}catch(e){next(e)}});
app.patch('/api/appointments/:id',protect,async(req,res,next)=>{try{const item=await Appointment.findById(req.params.id);if(!item)return res.status(404).json({message:'Appointment not found'});if(req.staffRole==='doctor'&&(String(item.assignedDoctor)!==String(req.doctor._id)||req.body.status!=='Completed'||Object.keys(req.body).some(key=>key!=='status')))return res.status(403).json({message:'Doctors may only complete their assigned appointments'});const scheduleChanged=req.body.date!==undefined||req.body.time!==undefined;const allowed=['status','date','time','service','reason','message'];for(const key of allowed)if(req.body[key]!==undefined)item[key]=req.body[key];if(item.status==='Cancelled'||item.status==='Completed')item.slotKey=undefined;else{const mainDoctor=await mainDoctorQuery();if(!mainDoctor)return res.status(503).json({message:'Main Doctor account is unavailable'});const date=item.date.toISOString().slice(0,10);if(scheduleChanged&&!(await availableSlots(date,item._id))?.includes(item.time))return res.status(409).json({message:'That appointment time is no longer available'});if(!item.mainDoctor||scheduleChanged){item.mainDoctor=mainDoctor._id;item.slotKey=`${mainDoctor._id}:${date}:${item.time}`;}}await item.save();await item.populate('patient doctor service assignedDoctor');res.json(item)}catch(e){if(e.code===11000)return res.status(409).json({message:'That appointment time is no longer available'});next(e)}});
function validFileSignature(buffer,mime){if(mime==='application/pdf')return buffer.subarray(0,5).toString()==='%PDF-';if(mime==='image/png')return buffer.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10]));if(mime==='image/jpeg')return buffer[0]===255&&buffer[1]===216&&buffer[2]===255;if(mime==='image/webp')return buffer.subarray(0,4).toString()==='RIFF'&&buffer.subarray(8,12).toString()==='WEBP';return false;}
function handleClinicalUpload(req,res,next){upload.single('file')(req,res,error=>{if(error){if(error instanceof multer.MulterError)error.status=error.code==='LIMIT_FILE_SIZE'?413:400;return next(error);}next();});}
app.post('/api/clinical/patients/:id/visits',protect,authorizePatient,async(req,res,next)=>{try{const allowed=['appointment','visitDate','mainComplaint','symptoms','painLevel','duration','clinicalExamination','diagnosis','affectedTeeth','treatmentRecommendation','treatmentPerformed','treatmentStatus','treatmentCost','notes','followUpDate','followUpReason','followUpNotes','patientVisible'];const values={patient:req.params.id,...(req.staffRole==='doctor'?{doctor:req.doctor._id}:{})};for(const key of allowed)if(req.body[key]!==undefined)values[key]=req.body[key];if(values.appointment&&!await Appointment.exists({_id:values.appointment,patient:req.params.id}))return res.status(400).json({message:'Appointment does not belong to this patient'});const visit=await Visit.create(values);res.status(201).json(visit)}catch(e){next(e)}});
app.post('/api/clinical/visits/:id/prescriptions',protect,authorizeVisit,async(req,res,next)=>{try{const visit=await Visit.findById(req.params.id);visit.prescriptions.push(req.body);await visit.save();res.status(201).json(visit)}catch(e){next(e)}});
app.post('/api/clinical/visits/:id/tests',protect,authorizeVisit,async(req,res,next)=>{try{const visit=await Visit.findById(req.params.id);visit.tests.push(req.body);await visit.save();res.status(201).json(visit)}catch(e){next(e)}});
app.patch('/api/clinical/visits/:id',protect,authorizeVisit,async(req,res,next)=>{try{const visit=await Visit.findById(req.params.id);for(const key of ['patientVisible','followUpDate','followUpReason','followUpNotes','followUpCompletedAt','notes'])if(req.body[key]!==undefined)visit[key]=req.body[key];await visit.save();res.json(visit)}catch(e){next(e)}});
app.get('/api/clinical/visits/:id/documents',protect,authorizeVisit,async(req,res,next)=>{try{res.json(await MedicalDocument.find({visit:req.params.id}).select('-storedName').sort('-createdAt'))}catch(e){next(e)}});
app.post('/api/clinical/patients/:patientId/visits/:visitId/documents',protect,authorizePatient,handleClinicalUpload,async(req,res,next)=>{try{if(!req.file)return res.status(400).json({message:'Choose a file to upload'});const visit=await Visit.findOne({_id:req.params.visitId,patient:req.params.patientId});if(!visit){unlinkSync(req.file.path);return res.status(404).json({message:'Visit not found'});}const buffer=readFileSync(req.file.path);if(!validFileSignature(buffer,req.file.mimetype)){unlinkSync(req.file.path);return res.status(400).json({message:'File content does not match an allowed PDF or image type'});}const categories=['X-ray','Image','Test report','Medical document','Other'];const category=categories.includes(req.body.category)?req.body.category:'Other';const testId=req.body.testId||null;const test=testId?visit.tests.id(testId):null;if(testId&&!test){unlinkSync(req.file.path);return res.status(400).json({message:'Test is not part of this visit'});}const originalName=path.basename(req.file.originalname).replace(/[\u0000-\u001f]/g,'').slice(0,180)||'clinical-file';const document=await MedicalDocument.create({patient:visit.patient,visit:visit._id,testId,doctor:req.doctor?._id,originalName,storedName:req.file.filename,mimeType:req.file.mimetype,size:req.file.size,category,status:'Uploaded',doctorNote:String(req.body.doctorNote||'').slice(0,2000),patientVisible:req.body.patientVisible==='true'});visit.documents.push(document._id);if(test){test.reportId=document._id;test.status='Completed';if(req.body.result!==undefined)test.result=String(req.body.result).slice(0,4000);}await visit.save();const output=document.toObject();delete output.storedName;res.status(201).json(output)}catch(e){if(req.file&&e.name!=='MongoServerError')try{unlinkSync(req.file.path)}catch{}next(e)}});
app.get('/api/clinical/documents/:id/download',protect,authorizeDocument,async(req,res,next)=>{try{const document=await MedicalDocument.findById(req.params.id);const filePath=path.resolve(uploadDirectory,document.storedName);if(!filePath.startsWith(`${uploadDirectory}${path.sep}`))return res.status(400).json({message:'Invalid document path'});res.download(filePath,document.originalName,error=>{if(error&&!res.headersSent)next(error);});}catch(e){next(e)}});
app.get('/api/patient/documents/:id/download',protectPatient,async(req,res,next)=>{try{const document=await MedicalDocument.findOne({_id:req.params.id,patient:req.patient._id,patientVisible:true});if(!document)return res.status(404).json({message:'Document not found'});const filePath=path.resolve(uploadDirectory,document.storedName);if(!filePath.startsWith(`${uploadDirectory}${path.sep}`))return res.status(400).json({message:'Invalid document path'});res.download(filePath,document.originalName,error=>{if(error&&!res.headersSent)next(error);});}catch(e){next(e)}});
app.delete('/api/clinical/documents/:id',protect,authorizeDocument,async(req,res,next)=>{try{const document=await MedicalDocument.findById(req.params.id);const filePath=path.resolve(uploadDirectory,document.storedName);if(!filePath.startsWith(`${uploadDirectory}${path.sep}`))return res.status(400).json({message:'Invalid document path'});try{unlinkSync(filePath)}catch(error){if(error.code!=='ENOENT')throw error;}await Promise.all([MedicalDocument.deleteOne({_id:document._id}),Visit.updateOne({_id:document.visit},{$pull:{documents:document._id}})]);res.json({message:'Document deleted'})}catch(e){next(e)}});
app.get('/api/reviews/all',protectAdmin,async(req,res,next)=>{try{res.json(await Review.find().sort('-createdAt'))}catch(e){next(e)}});
app.use(notFound);app.use(errorHandler);
const port=process.env.PORT||5000; connectDatabase().then(async()=>{if(process.env.ADMIN_EMAIL&&process.env.ADMIN_PASSWORD&&!await Admin.exists({email:process.env.ADMIN_EMAIL}))await Admin.create({email:process.env.ADMIN_EMAIL,password:process.env.ADMIN_PASSWORD});app.listen(port,()=>console.log(`API running on ${port}`))}).catch(err=>{console.error(err);process.exit(1)});
